
name: myapp
description: "Afercon Xpress: Entregas rápidas e seguras. Conecte-se a motoristas, envie as suas encomendas e acompanhe o percurso em tempo real. Simples, rápido e fiável."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  provider: ^6.1.5+1
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  go_router: ^14.1.0
  timeago: ^3.7.1
  firebase_messaging: ^14.9.0
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "assets/afercon-xpress.png"

flutter:
  uses-material-design: true
  assets:
    - assets/

