
name: myapp
description: "Afercon Xpress: Entregas rápidas e seguras. Conecte-se a motoristas, envie as suas encomendas e acompanhe o percurso em tempo real. Simples, rápido e fiável."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  intl: ^0.20.2
  url_launcher: ^6.3.0
  go_router: ^17.0.0
  timeago: ^3.6.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  audioplayers: ^6.0.0
  image_picker: ^1.2.1
  firebase_storage: ^13.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "assets/afercon-xpress.png"

flutter:
  uses-material-design: true
  assets:
    - assets/

