
name: myapp
description: "Afercon Xpress: Entregas rápidas e seguras. Conecte-se a motoristas, envie as suas encomendas e acompanhe o percurso em tempo real. Simples, rápido e fiável."
publish_to: 'none' 
version: 1.0.0+3

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  # Firebase - Versões atualizadas e compatíveis
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  firebase_messaging: ^14.9.1
  firebase_storage: ^11.7.4
  
  # Pacotes com versões corrigidas
  go_router: ^14.1.0 
  intl: ^0.19.0
  flutter_local_notifications: ^17.1.2

  url_launcher: ^6.3.0
  timeago: ^3.6.1
  audioplayers: ^6.0.0
  image_picker: ^1.2.1
  firebase_crashlytics: ^3.5.7
  firebase_analytics: ^10.10.7
  badges: ^3.1.2
  permission_handler: ^12.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "assets/afercon-xpress.png"

flutter:
  uses-material-design: true
  assets:
    - assets/

